name: Sheet to Json Workflow

on:
  schedule:
    # every 10 minutes the job will run
    - cron:  '*/10 * * * *'
  push:
    branches:
      - master

jobs:
  update-json-data:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v1
      - name: push
        run: |
           bash ./pushthejson
           echo "the job completed"
        env:
            GITHUB_TOKEN: ${{ secrets.github_token }}
            BOT_TOKEN: ${{ secrets.bot_token }}


#trigger the action
#trigger the action by remove this line